[package]
name = "grasshooper"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
notion = "0.6.0"
dotenvy = "0.15.7"
dialoguer = "0.12.0"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
chrono = "0.4.42"
ping = "0.7.0"
